import type { EnhancedStore, Slice } from "@reduxjs/toolkit";
import type { EmptyEventMap, EventMap, FacadeCommandFunction, FacadeCommandResult, IgniteCoreReturn } from "ignite-core";
import type { ReduxBlueprintConfig, ReduxBlueprintSource, ReduxCommandActorFor, ReduxInstanceConfig, ReduxInstanceSource } from "../types";
import type { InferStateAndEvent } from "../utils/igniteRedux";
type ReduxCoreOptions<Host = unknown> = ReduxBlueprintConfig<() => EnhancedStore, EventMap, Record<string, unknown>, FacadeCommandResult, Host> | ReduxInstanceConfig<ReduxInstanceSource, EventMap, Record<string, unknown>, FacadeCommandResult, Host> | ReduxBlueprintConfig<Slice, EventMap, Record<string, unknown>, FacadeCommandResult, Host>;
export declare function igniteCoreRedux<Source extends ReduxBlueprintSource, Events extends EventMap = EmptyEventMap, StatesResult extends Record<string, unknown> = Record<never, never>, CommandsResult extends Record<never, FacadeCommandFunction> = Record<never, FacadeCommandFunction>, Host = unknown>(options: ReduxBlueprintConfig<Source, Events, StatesResult, CommandsResult, Host>): IgniteCoreReturn<InferStateAndEvent<Source>["State"], InferStateAndEvent<Source>["Event"], InferStateAndEvent<Source>["State"], StatesResult, ReduxCommandActorFor<Source>, CommandsResult, Events, Host>;
export declare function igniteCoreRedux<StoreInstance extends ReduxInstanceSource, Events extends EventMap = EmptyEventMap, StatesResult extends Record<string, unknown> = Record<never, never>, CommandsResult extends Record<never, FacadeCommandFunction> = Record<never, FacadeCommandFunction>, Host = unknown>(options: ReduxInstanceConfig<StoreInstance, Events, StatesResult, CommandsResult, Host>): IgniteCoreReturn<InferStateAndEvent<StoreInstance>["State"], InferStateAndEvent<StoreInstance>["Event"], InferStateAndEvent<StoreInstance>["State"], StatesResult, ReduxCommandActorFor<StoreInstance>, CommandsResult, Events, Host>;
export declare function igniteCoreRedux<Host = unknown>(options: ReduxCoreOptions<Host>): IgniteCoreReturn<InferStateAndEvent<ReduxBlueprintSource | ReduxInstanceSource>["State"], InferStateAndEvent<ReduxBlueprintSource | ReduxInstanceSource>["Event"], InferStateAndEvent<ReduxBlueprintSource | ReduxInstanceSource>["State"], Record<string, unknown>, ReduxCommandActorFor<ReduxBlueprintSource | ReduxInstanceSource>, FacadeCommandResult, EventMap, Host>;
export {};
//# sourceMappingURL=redux.d.ts.map