name: Refresh NPM Token

on:
  schedule:
    - cron: "0 0 * * 0" # Every Sunday at midnight UTC

jobs:
  refresh-token:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Test refresh token script
        run: npm run test:node

      - name: Refresh NPM Token
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO_NAME: ${{ github.repository }}
        run: node scripts/refresh-npm-token.js
