name: Renovate

on:
  workflow_dispatch:
  schedule:
    - cron: "0 7 * * 1"
    - cron: "0 8 * * 1"
    - cron: "0 9 * * 1"

permissions:
  contents: read

jobs:
  renovate:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          persist-credentials: false

      - name: Run self-hosted Renovate
        uses: renovatebot/github-action@v46.1.18
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
        env:
          LOG_LEVEL: info
          RENOVATE_PLATFORM: github
          RENOVATE_REPOSITORIES: 0xjcf/ignite-element
          RENOVATE_REQUIRE_CONFIG: required
          RENOVATE_ONBOARDING: "false"
